### PR TITLE
fixed kustomize docs

### LINKED ISSUE #1073: v1alpha1.ScrapeConfigSpec metricsPath is not converted
The `metricsPath` field of [v1alpha1.ScrapeConfigSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1alpha1.ScrapeConfigSpec) is not converted by the operator. [v1beta1.VMScrapeConfigSpec](https://docs.victoriametrics.com/operator/api/#vmscrapeconfigspec) has a `path` field, but the operator does not handle the translation.

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
related https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6790
also fixes #1073

### CODE REVIEW

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 1]
```diff
@@ -143,6 +143,7 @@ func ConvertScrapeConfig(promscrapeConfig *promv1alpha1.ScrapeConfig, conf *conf
 	cs.Annotations = converter.FilterPrefixes(promscrapeConfig.Annotations, conf.FilterPrometheusConverterAnnotationPrefixes)
 	cs.Spec.RelabelConfigs = converter.ConvertRelabelConfig(promscrapeConfig.Spec.RelabelConfigs)
 	cs.Spec.MetricRelabelConfigs = converter.ConvertRelabelConfig(promscrapeConfig.Spec.MetricRelabelConfigs)
+	cs.Spec.Path = *promscrapeConfig.Spec.MetricsPath
```
Comment (f41gh7) [inline internal/controller/operator/converter/v1alpha1/apis.go]: I think, it's better to use ptr.Deref, otherwise operator will crash with panic at null metricsPath

Comment (f41gh7) [reply internal/controller/operator/converter/v1alpha1/apis.go]: See failed tests

Comment (AndrewChubatiuk) [reply internal/controller/operator/converter/v1alpha1/apis.go]: updated

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!
