### PR TITLE
convert: support prom alertmanagerconfig spec.muteTimeIntervals conve…

### LINKED ISSUE #1783: Failed to convert `time_interval` settings from Prometheus AlertmanagerConfig
The CR conversion of `time_interval` definition seems to be missing in [ConvertAlertmanagerConfig function](https://github.com/VictoriaMetrics/operator/blob/e07f4c2b6d3ecd049b829e22f1fd86c26868666d/internal/controller/operator/converter/v1alpha1/apis.go#L88).

Sample original config:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
spec:
  muteTimeIntervals:
    - name: holidays
      timeIntervals:
        - weekdays:
            - saturday
            - sunday
  receivers:
    - name: default-receiver
  route:
    matchers:
      - matchType: '='
        name: namespace
        value: monitor
    muteTimeIntervals:
      - holidays
    receiver: default-receiver
```
Expected conversion result:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: alertmanager-config
spec:
  time_intervals:
    - name: holidays
      time_intervals:
        - weekdays:
            - saturday
            - sunday
  receivers:
    - name: default-receiver
  route:
    matchers:
      - namespace="monitor"
    mute_time_intervals
      - holidays
    receiver: default-receiver
```
Actual result:
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: alertmanager-config
spec:
  receivers:
    - name: default-receiver
  route:
    matchers:
      - namespace="monitor"
    receiver: default-receiver
```

AlertmanagerConfig 'muteTimeInterval' field definition reference:
https://github.com/prometheus-operator/prometheus-operator/blob/4cadbf7736760a0422072494ec265196d9f8db29/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L150

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
fixes https://github.com/VictoriaMetrics/operator/issues/1783

---
## Summary by cubic
Adds conversion for Prometheus AlertmanagerConfig spec.muteTimeIntervals to VMAlertmanagerConfig spec.timeIntervals so mute windows are preserved and applied correctly. Fixes #1783.

- **Bug Fixes**
  - Map name, times, weekdays, daysOfMonth (start:end), months, and years from Prom MuteTimeIntervals to VM TimeIntervals.
  - Refactor matcher conversion for routes and inhibit rules; update tests to assert time interval mapping and add a changelog entry.

<sup>Written for commit 1e9ab9dad30f2cc0bf60121ec9af13b19f5d2234. Summary will update on new commits.</sup>

### CODE REVIEW

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 1]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
...
+			Weekdays:    toStringSlice(promTI.Weekdays),
+			DaysOfMonth: convertDaysOfMonth(promTI.DaysOfMonth),
+			Months:      toStringSlice(promTI.Months),
+			Years:       toStringSlice(promTI.Years),
+		})
+	}
+	return vmTIs
+}
+
+func convertTimeIntervals(promTIs []promv1alpha1.MuteTimeInterval) []vmv1beta1.TimeIntervals {
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]:
```suggestion
func convertMuteTimeIntervals(promTIs []promv1alpha1.MuteTimeInterval) []vmv1beta1.TimeIntervals {
```

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 2]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
...
+		return nil
+	}
+	vmDoMs := make([]string, 0, len(promDoMs))
+	for _, promDoM := range promDoMs {
+		vmDoMs = append(vmDoMs, fmt.Sprintf("%d:%d", promDoM.Start, promDoM.End))
+	}
+	return vmDoMs
+}
+
+func convertTimeInterval(promTIs []promv1alpha1.TimeInterval) []vmv1beta1.TimeInterval {
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]:
```suggestion
func convertPromTimeInterval(promTIs []promv1alpha1.TimeInterval) []vmv1beta1.TimeInterval {
```
or maybe just add the function docstring

**Comment by AndrewChubatiuk** [comment]
@vrutkovs thanks for review
addressed you comments

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 3]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
 	return &r, nil
 }
 
-func convertInhibitRules(promIRs []promv1alpha1.InhibitRule) []vmv1beta1.InhibitRule {
+func convertPromTimeRanges(promTRs []promv1alpha1.TimeRange) []vmv1beta1.TimeRange {
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]: This needs unit tests

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 4]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
...
+func toStringSlice[T stringLike](promItems []T) []string {
+	if promItems == nil {
+		return nil
+	}
+	vmItems := make([]string, 0, len(promItems))
+	for _, promItem := range promItems {
+		vmItems = append(vmItems, string(promItem))
+	}
+	return vmItems
+}
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]:
```suggestion
func convertPromRangeToString[T ~string](s T) string {
	return string(s)
}
```

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 5]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
...
+
+func convertPromTimeInterval(promTIs []promv1alpha1.TimeInterval) []vmv1beta1.TimeInterval {
+	if promTIs == nil {
+		return nil
+	}
+	vmTIs := make([]vmv1beta1.TimeInterval, 0, len(promTIs))
+	for _, promTI := range promTIs {
+		vmTIs = append(vmTIs, vmv1beta1.TimeInterval{
+			Times:       convertPromTimeRanges(promTI.Times),
+			Weekdays:    toStringSlice(promTI.Weekdays),
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]:
```suggestion
			Weekdays:    convertSliceStruct(promTI.Weekdays, convertPromRangeToString),
```

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 6]
```diff
@@ -68,18 +68,89 @@ func convertRoute(promRoute *promv1alpha1.Route) (*vmv1beta1.Route, error) {
...
+			DaysOfMonth: convertPromDaysOfMonth(promTI.DaysOfMonth),
+			Months:      toStringSlice(promTI.Months),
+			Years:       toStringSlice(promTI.Years),
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go]:
```suggestion
			Months:      convertSliceStruct(promTI.Months, convertPromRangeToString),
			Years:       convertSliceStruct(promTI.Years, convertPromRangeToString),
```

**Review by vrutkovs — CHANGES_REQUESTED** [review]

File: internal/controller/operator/converter/v1alpha1/apis.go (hunk 6 above)
Comment (AndrewChubatiuk) [reply internal/controller/operator/converter/v1alpha1/apis.go]: @vrutkovs updated PR

File: internal/controller/operator/converter/v1alpha1/apis.go [hunk 7]
```diff
@@ -18,24 +18,18 @@ import (
...
-		}
-		if pm.MatchType == "" {
-			pm.MatchType = "="
+func convertPromMatcher(promMatcher promv1alpha1.Matcher) string {
+	if promMatcher.MatchType == "" {
+		if len(promMatcher.Value) > 0 {
+			promMatcher.MatchType = "=~"
+		} else {
+			promMatcher.MatchType = "="
 		}
```
Comment (vrutkovs) [inline internal/controller/operator/converter/v1alpha1/apis.go:26]:
```suggestion
	if promMatcher.MatchType == "" {
		promMatcher.MatchType = "="
		if len(promMatcher.Value) > 0 {
			promMatcher.MatchType = "=~"
		}
}
```

**Review by vrutkovs — APPROVED** [review]
